"use client"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useContext, useState } from "react";
import { create } from "zustand";
import { set } from "react-hook-form";
import {Provider} from "react-redux"


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  

  
  
  // const useBearStore = create((set) => ({
  //   linkProfile:linkProfile,
  //   setLinkProfile:setLinkProfile
  // }))

  // console.log(useBearStore((set) => set))

  return (
    <html lang="en">     
      
          <body className={inter.className}>{children }</body>
    
    </html>
  );
}
